### ISSUE TITLE
👎

### ISSUE THREAD

**Issue by mr-nv** [fuckyouthinkimboogieman/fuck-badannotation-crashers#1]

**Comment by fuckyouthinkimboogieman** [comment]
👍

**Comment by fuckyouthinkimboogieman** [comment]
![image](https://user-images.githubusercontent.com/43454376/132139190-44814e0d-8327-413c-8bff-d0e2f7e6e7c0.png)

**Comment by fuckyouthinkimboogieman** [comment]
![image](https://user-images.githubusercontent.com/43454376/132139200-d7f7a515-c623-4878-ba13-bf07e99e18e8.png)
